In [2]:
import numpy as np
import pandas as pd

In [3]:
d = pd.Series ([4.5, 7.2, -5.3, 3.61], index=["d", "b", "a", "c"])
d

d    4.50
b    7.20
a   -5.30
c    3.61
dtype: float64

#### Reindexing

In [4]:
d2 = d.reindex(["e", "a", "d", "c", "b"])
d2

e     NaN
a   -5.30
d    4.50
c    3.61
b    7.20
dtype: float64

In [5]:
# coding challange, get the sorted version of d2
d2 = d.reindex(sorted(["e", "a", "d", "c", "b"]))
d2

a   -5.30
b    7.20
c    3.61
d    4.50
e     NaN
dtype: float64

#### Forward -filling using reindexing

In [9]:
d = pd.Series(["apple", "pear", "banana"], index= [0, 2, 7])
d
print (d.reindex(np.arange (12)), "\n")    # adding more indexes

0      apple
1        NaN
2       pear
3        NaN
4        NaN
5        NaN
6        NaN
7     banana
8        NaN
9        NaN
10       NaN
11       NaN
dtype: object

In [10]:
print (d. reindex(np.arange (12), method="ffill"))   # to fill up all Nan

0      apple
1      apple
2       pear
3       pear
4       pear
5       pear
6       pear
7     banana
8     banana
9     banana
10    banana
11    banana
dtype: object

In [12]:
print (d.reindex(np.arange (12), method="nearest"))  # near indicing

0      apple
1       pear
2       pear
3       pear
4       pear
5     banana
6     banana
7     banana
8     banana
9     banana
10    banana
11    banana
dtype: object

#### Reindexing Rows and Columns

In [21]:
provinces = pd.DataFrame(np.arange (9).reshape((3, 3)), 
                           index= ["a", "c", "d"],  # rows
                           columns= ["Ontario" , "Quebec", "Alberta"])
print(provinces)

   Ontario  Quebec  Alberta
a        0       1        2
c        3       4        5
d        6       7        8

In [22]:
# Row reindexing
p2 = provinces. reindex(index=["a", "b", "c", "d"])
p2

   Ontario  Quebec  Alberta
a      0.0     1.0      2.0
b      NaN     NaN      NaN
c      3.0     4.0      5.0
d      6.0     7.0      8.0

In [27]:
p3 = provinces.reindex(columns=["Alberta", "Ontario", "Alberta"])
p3

   Alberta  Ontario  Alberta
a        2        0        2
c        5        3        5
d        8        6        8

#### Drop/remove values

In [28]:
t = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])
t

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [29]:
t.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [31]:
t.drop(['a','e'])

b    1.0
c    2.0
d    3.0
dtype: float64

In [32]:
# dropping by axis
p_copy = provinces.copy()
p_copy

   Ontario  Quebec  Alberta
a        0       1        2
c        3       4        5
d        6       7        8

In [35]:
p_copy.drop(['a','c'], axis=0) # row drop

   Ontario  Quebec  Alberta
d        6       7        8

In [36]:
p_copy.drop(["Ontario"], axis=1)

   Quebec  Alberta
a       1        2
c       4        5
d       7        8

In [40]:
num = pd.Series([1,2,3], index=[2,0,1])
num

2    1
0    2
1    3
dtype: int64

In [43]:
print(num[[2,0]])   # helps changing positions

2    1
0    2
dtype: int64

In [44]:
num.index

Index([2, 0, 1], dtype='int64')

### Loc (label-based) and iloc (int-based indexing)

In [46]:
p_copy

   Ontario  Quebec  Alberta
a        0       1        2
c        3       4        5
d        6       7        8

In [53]:
print(p_copy.loc[['a','c'], ["Ontario","Alberta"]])

   Ontario  Alberta
a        0        2
c        3        5

In [48]:
print(p_copy.iloc[[0,2]])  # gives the data by position

   Ontario  Quebec  Alberta
a        0       1        2
d        6       7        8

#### index with slicing

In [51]:
print(p_copy.loc['a':'c', :])

   Ontario  Quebec  Alberta
a        0       1        2
c        3       4        5

In [54]:
print(p_copy.iloc[0:3,:])

   Ontario  Quebec  Alberta
a        0       1        2
c        3       4        5
d        6       7        8

#### Boolean Indexing

In [59]:
grades = pd.DataFrame([[75, 45, 60], [100, 85, 92],
                      [55, 78, 0], [14, 88, 49]], 
                     columns=["Mark", "Kelly", "Idra"], 
                     index=["Exam1", "Exam2", "Exam3", "Exam4"])
grades

       Mark  Kelly  Idra
Exam1    75     45    60
Exam2   100     85    92
Exam3    55     78     0
Exam4    14     88    49

In [60]:
grades.shape

(4, 3)

In [61]:
grades >= 50

        Mark  Kelly   Idra
Exam1   True  False   True
Exam2   True   True   True
Exam3   True   True  False
Exam4  False   True  False

In [63]:
grades[grades<=50]

       Mark  Kelly  Idra
Exam1   NaN   45.0   NaN
Exam2   NaN    NaN   NaN
Exam3   NaN    NaN   0.0
Exam4  14.0    NaN  49.0

In [64]:
grades[grades>=50]

        Mark  Kelly  Idra
Exam1   75.0    NaN  60.0
Exam2  100.0   85.0  92.0
Exam3   55.0   78.0   NaN
Exam4    NaN   88.0   NaN

In [67]:
grades[(grades>=70) & (grades< 80)]

       Mark  Kelly  Idra
Exam1  75.0    NaN   NaN
Exam2   NaN    NaN   NaN
Exam3   NaN   78.0   NaN
Exam4   NaN    NaN   NaN

In [70]:
# alternative way
idx = grades[(grades>=70) & (grades< 80)]
idx

       Mark  Kelly  Idra
Exam1  75.0    NaN   NaN
Exam2   NaN    NaN   NaN
Exam3   NaN   78.0   NaN
Exam4   NaN    NaN   NaN