In [1]:
import numpy as np
import pandas as pd

### Series 
similar to array but 1D and same type

In [13]:
d = pd.Series([4,2,100,-35])
len(d)

4

In [14]:
print(type(d))
print(d.dtype)

<class 'pandas.core.series.Series'>
int64

In [15]:
print(d.array, "\n--------")
print(d.index)

<NumpyExtensionArray>
[4, 2, 100, -35]
Length: 4, dtype: int64
--------
RangeIndex(start=0, stop=4, step=1)

#### Series Index

In [26]:
d1 = pd.Series([4,2,100,-35], index=["a","b","c","d"])
print(d1.array, "\n--------")
d1.index
d1['b']    # you give the position name to series by indexing it

<NumpyExtensionArray>
[4, 2, 100, -35]
Length: 4, dtype: int64
--------

2

In [31]:
print(d1['a']+d1['c'], "\n")
print(d1[['a','b','c']], "\n")    # need 2 brackets
print(d1['b':'d'], "\n")
print(d1[['b','d']], "\n")

104

a      4
b      2
c    100
dtype: int64

b      2
c    100
d    -35
dtype: int64

b     2
d   -35
dtype: int64

#### NumPy operations in Series

In [36]:
d2 = d1.copy()
print(d2,"\n-----")
print(d2*2,"\n-----")
print('b' in d2)

a      4
b      2
c    100
d    -35
dtype: int64
-----
a      8
b      4
c    200
d    -70
dtype: int64
-----
True

#### Serires from Dictionaries

In [66]:
prov_dict = {
    "Ontario": 7000,
    "Quebec": 45000,
    "British Columbia": 29500
}

prov = pd.Series(prov_dict)
print(prov,"\n-----")

Ontario              7000
Quebec              45000
British Columbia    29500
dtype: int64
-----

In [67]:
print(prov*2,"\n------")
prov['Ontario']

Ontario             14000
Quebec              90000
British Columbia    59000
dtype: int64
------

7000

In [68]:
prov['Ontario'] *2

14000

In [69]:
prov_codes = ["Ontario","Quebec","Alberta"]
prov2 = pd.Series(prov_dict, index=prov_codes)
print(prov2)

Ontario     7000.0
Quebec     45000.0
Alberta        NaN
dtype: float64

#### Index alignment

In [70]:
prov + prov2

Alberta                 NaN
British Columbia        NaN
Ontario             14000.0
Quebec              90000.0
dtype: float64

In [71]:
prov.array + prov2.array

<NumpyExtensionArray>
[14000.0, 90000.0, nan]
Length: 3, dtype: float64

#### update index

In [72]:
prov2.index = ["Ontario","Quebec","British Columbia"]
print(prov2)
prov + prov2

Ontario              7000.0
Quebec              45000.0
British Columbia        NaN
dtype: float64

Ontario             14000.0
Quebec              90000.0
British Columbia        NaN
dtype: float64

### Data Frames

In [73]:
data = {"province": ["Ontario", "Ontario", "Ontario", "Alberta", "Alberta", "Alberta"],
"year": [2010, 2011, 2012, 2011, 2012, 2013],
"pop": [13.1, 12.9, 14.6, 3.6, 4.3, 4.0]}
frame = pd. DataFrame(data)
frame
print(data)

{'province': ['Ontario', 'Ontario', 'Ontario', 'Alberta', 'Alberta', 'Alberta'], 'year': [2010, 2011, 2012, 2011, 2012, 2013], 'pop': [13.1, 12.9, 14.6, 3.6, 4.3, 4.0]}

In [74]:
frame.tail()

  province  year   pop
1  Ontario  2011  12.9
2  Ontario  2012  14.6
3  Alberta  2011   3.6
4  Alberta  2012   4.3
5  Alberta  2013   4.0

In [75]:
frame.head()

  province  year   pop
0  Ontario  2010  13.1
1  Ontario  2011  12.9
2  Ontario  2012  14.6
3  Alberta  2011   3.6
4  Alberta  2012   4.3

In [76]:
# reordering colums

pd.DataFrame(data, columns=["year","province","pop"])

   year province   pop
0  2010  Ontario  13.1
1  2011  Ontario  12.9
2  2012  Ontario  14.6
3  2011  Alberta   3.6
4  2012  Alberta   4.3
5  2013  Alberta   4.0

In [79]:
# Missing columns

frame2 = pd.DataFrame(data, columns= ["year", "province", "pop","Birth rate"])
frame2

   year province   pop Birth rate
0  2010  Ontario  13.1        NaN
1  2011  Ontario  12.9        NaN
2  2012  Ontario  14.6        NaN
3  2011  Alberta   3.6        NaN
4  2012  Alberta   4.3        NaN
5  2013  Alberta   4.0        NaN

In [84]:
# retrieve column
frame2.province

0    Ontario
1    Ontario
2    Ontario
3    Alberta
4    Alberta
5    Alberta
Name: province, dtype: object

In [85]:
frame2.province == frame2['province']

0    True
1    True
2    True
3    True
4    True
5    True
Name: province, dtype: bool

In [90]:
# Alignment by index
val = pd.Series([-1.2, -1.5, -1.7, 999], index=(2, "four", "five", 5))
val
frame2 ["Birth rate"] = val
frame2

   year province   pop  Birth rate
0  2010  Ontario  13.1         NaN
1  2011  Ontario  12.9         NaN
2  2012  Ontario  14.6        -1.2
3  2011  Alberta   3.6         NaN
4  2012  Alberta   4.3         NaN
5  2013  Alberta   4.0       999.0